development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
test:
  clients:
    default:
      database: boba_tier_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
